# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-03 09:38
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnauthentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeruser',
            name='confirm_password',
            field=models.CharField(default='s1', max_length=20, validators=[django.core.validators.RegexValidator('^(\\w+\\d+|\\d+\\w+)+$', message='Password should be a combination of Alphabets and Numbers')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registeruser',
            name='password',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^(\\w+\\d+|\\d+\\w+)+$', message='Password should be a combination of Alphabets and Numbers')]),
        ),
    ]
