# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-09 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmcas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(help_text='Enter Product Stock Keeping Unit', max_length=13)),
                ('barcode', models.CharField(help_text='Enter Product Barcode (ISBN, UPC ...)', max_length=13)),
                ('title', models.CharField(help_text='Enter Product Title', max_length=200)),
                ('description', models.TextField(help_text='Enter Product Description')),
                ('unitCost', models.FloatField(help_text='Enter Product Unit Cost')),
                ('unit', models.CharField(help_text='Enter Product Unit ', max_length=10)),
                ('quantity', models.FloatField(help_text='Enter Product Quantity')),
                ('minQuantity', models.FloatField(help_text='Enter Product Min Quantity')),
            ],
        ),
    ]
