# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-29 08:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('one2one', '0002_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='clinic',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child1', to='one2one.Country'),
        ),
        migrations.AddField(
            model_name='country',
            name='clinic_name',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='country',
            name='sub_clinic',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child2', to='one2one.Country'),
        ),
        migrations.AddField(
            model_name='country',
            name='subclinic_name',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
