# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-31 02:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('one2one', '0003_auto_20190329_0823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='clinic',
        ),
        migrations.RemoveField(
            model_name='country',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='country',
            name='sub_clinic',
        ),
        migrations.RemoveField(
            model_name='country',
            name='subclinic_name',
        ),
    ]
